sudo: true
language: rust

matrix:
    fast_finish: true
    include:
        - rust: nightly
          env: FEATURES="--all-features"
        - rust: nightly
          env: FEATURES="--features nightly"
        - rust: beta
        - rust: beta
          env: FEATURES="--features serde"
        - rust: stable
        - rust: stable
          env: FEATURES="--features serde"

cache:
    apt: true
    directories:
        - target/debug/deps
        - target/debug/build

script:
  - cargo build --verbose $FEATURES
  - cargo test --verbose $FEATURES

notifications:
    email: false
