[package]

name = "unicase"
version = "2.0.0-a.0"
authors = ["Sean McArthur <sean.monstar@gmail.com>"]
description = "A case-insensitive wrapper around strings."
repository = "https://github.com/seanmonstar/unicase"
license = "MIT"
keywords = ["lowercase", "case", "case-insensitive"]

build = "build.rs"

[build-dependencies]
rustc_version = "0.2"

[features]
nightly = []
