[package]

name = "unicase"
version = "2.0.0"
authors = ["Sean McArthur <sean.monstar@gmail.com>"]
description = "A case-insensitive wrapper around strings."
repository = "https://github.com/seanmonstar/unicase"
license = "MIT/Apache-2.0"
keywords = ["lowercase", "case", "case-insensitive"]

exclude = [
    "scripts/"
]

build = "build.rs"

[features]
default = []

nightly = []

[dependencies]
serde = { version = "1.0", optional = true }

[build-dependencies]
version_check = "0.1"

[dev-dependencies]
serde_derive = "1.0"
serde_test = "1.0"

[package.metadata.docs.rs]
features = ["serde"]
